[package]
name = "test_no_std"
edition = "2024"

[dependencies]
# A renamed dependency also checks that macro expansions do not require the
# original crate name or direct dependencies on the logging backends.
trail = { package = "err_trail", path = "../err_trail" }
heapless = "0.8"
exit-no-std = "0.2.1"

[features]
tracing = ["trail/tracing"]
log = ["trail/log"]
defmt = ["trail/defmt"]

[lib]
path = "lib.rs"

[[bin]]
name = "test_no_std"
path = "main.rs"

# [profile.dev]
# panic = "abort"

# [profile.release]
# panic = "abort"
