[package]
name = "err_trail"
description = "Add context to errors through logging"
categories = ["rust-patterns", "no-std"]
version = "0.11.2"
edition = "2024"
license = "Apache-2.0"
documentation = "https://docs.rs/err_trail"
repository = "https://github.com/mcmah309/err_trail"

[dependencies]
err_trail_macros = { version = "0.11.2", path = "../err_trail_macros" }
tracing = { version = "0.1", default-features = false, optional = true }
log = { version = "0.4", default-features = false, optional = true }
defmt = { version = "1", default-features = false, optional = true }

[dev-dependencies]
defmt = { version = "1", features = ["unstable-test"] }
log = { version = "0.4", features = ["std"] }
trybuild = "1"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
tracing-test = { version = "0.2", features = ["no-env-filter"] }
flaky_test = "0.2"

[features]
default = []
tracing = ["dep:tracing", "err_trail_macros/tracing"]
log = ["dep:log", "err_trail_macros/log"]
defmt = ["dep:defmt", "err_trail_macros/defmt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
